#!/bin/bash -e
#===============================================================================
# Make Plots of Regressors
# Authors: Timothy R. Koscik, PhD
# Date: 2020-10-08
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
OPERATOR=${OPERATOR//@}
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch --------------------------------
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ ${EXIT_CODE} -eq 0 ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    writeBenchmark ${OPERATOR} ${HARDWARE} ${KERNEL} ${FCN_NAME} \
      ${PROC_START} ${PROC_STOP} ${EXIT_CODE}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hl --long regressor:,do-corr,dir-save:,title:,help,no-log -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
REGRESSOR=
DO_CORR="false"
TITLE=
DIR_SAVE=
HELP=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    --regressor) REGRESSOR="$2" ; shift 2 ;;
    --do-corr) DO_CORR="true" ; shift ;;
    --title) TITLE="$2" ; shift 2 ;;
    --dir-save) DIR_SAVE="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "TKNI: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  --regressor <value>     csv list of file paths *.1D regressor files'
  echo '  --do-corr                make a correlation plot as well'
  echo '  --title                override default plot title'
  echo '  --dir-save <value>       directory to save output, optional'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
FLS=(${REGRESSOR//,/ })
if [[ -z "${DIR_SAVE}" ]]; then DIR_SAVE=$(dirname ${FLS[0]}); fi
mkdir -p ${DIR_SAVE}

RFCN="Rscript ${TKNIPATH}/R/regressorPlot.R"
RFCN="${RFCN} regressor ${REGRESSOR}"
RFCN="${RFCN} dir-save ${DIR_SAVE}"
RFCN="${RFCN} docorr ${DO_CORR^^}"
if [[ -n ${TITLE} ]]; then RFCN="${RFCN} title '${TITLE}'"; fi
eval ${RFCN}

#===============================================================================
# End of Function
#===============================================================================
exit 0


