#!/bin/bash -e

#===============================================================================
# PIPELINE:      tkni
# WORKFLOW:      QCANAT
# DESCRIPTION:   Generate a quality control report for a participant after
#                processing pipelines are finished for anatomical images.
# AUTHOR:        Timothy R. Koscik, PhD
# DATE CREATED:  2026-01-27
# README:        
# DATE MODIFIED: 
# CHANGELOG:
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
FCN_NAME=${FCN_NAME%.*}
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
OPERATOR=${OPERATOR//@}
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch --------------------------------
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ ${EXIT_CODE} -eq 0 ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    writeBenchmark ${OPERATOR} ${HARDWARE} ${KERNEL} ${FCN_NAME} \
      ${PROC_START} ${PROC_STOP} ${EXIT_CODE}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hv --long pi:,project:,dir-project:,\
id:,dir-id:,base-img:,base-mod:,\
align-manual:,align-to:,\
fg-clip:,ants-template:,\
dir-scratch:,requires:,\
help,verbose,force -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values -----------------------------------------------------------
PI=
PROJECT=
DIR_PROJECT=
DIR_SCRATCH=
IDPFX=
IDDIR=
IDVARS="sub,ses"

DIR_RAW=
DIR_NATIVE=
DIR_ADD=
DIR_MASK=
DIR_LABEL
DIR_XFM=
DIR_POST=

MASK_FG=
MASK_BRAIN=
MASK_WM=
LABEL_TISSUE=

#METRICS="cjv,cnr,efc,fber,fwhm,snr_frame,snr_fg,snr_brain,snr_dietrich,wm2max"
# disabling option to select metrics, will require rework of output generation to implement
ADD_MEAN="true"
VOLUME="all"
REF_NATIVE=
LAB_GM=2
LAB_WM=4
LAB_DEEP=3
LAB_CSF=1
VOL_GM=1
VOL_WM=3
VOL_DEEP=2
VOL_CSF=4

HELP="false"
VERBOSE="false"
NO_PNG="false"
NO_RMD="false"
NO_SUMMARY="false"
NO_RAW="false"

PIPE=tkni
FLOW=${FCN_NAME//tkni}
REQUIRES=""
FORCE=false

# gather input options ---------------------------------------------------------
while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -v | --verbose) VERBOSE=true ; shift ;;
    -n | --no-png) NO_PNG=true ; shift ;;
    -r | --no-rmd) NO_RMD=true ; shift ;;
    --pi) PI="$2" ; shift 2 ;;
    --project) PROJECT="$2" ; shift 2 ;;
    --id) IDPFX="$2" ; shift 2 ;;
    --dir-id) IDDIR="$2" ; shift 2 ;;
    --force) FORCE="true" ; shift ;;
    --requires) REQUIRES="$2" ; shift 2 ;;
    --dir-project) DIR_PROJECT="$2" ; shift 2 ;;
    --dir-scratch) DIR_SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "TKNI: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help        display command help'
  echo '  -v | --verbose     add verbose output to log file'
  echo '  -n | --no-png      disable generating pngs of output'
  echo '  --pi               folder name for PI, no underscores'
  echo '                       default=evanderplas'
  echo '  --project          project name, preferrable camel case'
  echo '                       default=unitcall'
  echo '  --dir-project      project directory'
  echo '                     default=/data/x/projects/${PI}/${PROJECT}'
  echo '  --id               file prefix, usually participant identifier string'
  echo '                       e.g., sub-123_ses-20230111T1234_aid-4567'
  echo '  --dir-id           sub-directory corresponding to subject in BIDS'
  echo '  --dir-scratch      directory for temporary workspace'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
TIMESTAMP=$(date +%Y%m%dT%H%M%S)

# set project defaults ---------------------------------------------------------
if [[ -z ${PI} ]]; then
  echo "ERROR [${PIPE}:${FLOW}] PI must be provided"
  exit 1
fi
if [[ -z ${PROJECT} ]]; then
  echo "ERROR [${PIPE}:${FLOW}] PROJECT must be provided"
  exit 1
fi
if [[ -z ${DIR_PROJECT} ]]; then
  DIR_PROJECT=/data/x/projects/${PI}/${PROJECT}
fi
if [[ -z ${DIR_SCRATCH} ]]; then
  DIR_SCRATCH=${TKNI_SCRATCH}/${FLOW}_${PI}_${PROJECT}_${DATE_SUFFIX}
fi

# Check ID ---------------------------------------------------------------------
if [[ -z ${IDPFX} ]]; then
  echo "ERROR [${PIPE}:${FLOW}] ID Prefix must be provided"
  exit 1
fi
if [[ -z ${IDDIR} ]]; then
  TSUB=$(getField -i ${IDPFX} -f sub)
  TSES=$(getField -i ${IDPFX} -f ses)
  IDDIR=sub-${TSUB}
  if [[ -n ${TSES} ]]; then
    IDDIR="${IDDIR}/ses-${TSES}"
  fi
fi
# make ID String for output ------
HDR=${IDVARS}
IDVARS=(${IDVARS//,/ })
IDSTR=""
for i in "${IDVARS[@]}"; do IDSTR="${IDSTR},$(getField -i ${IDPFX} -f ${i})"; done
IDSTR=${IDSTR:1}

### PIPELINE
# Set default directories ------------------------------------------------------
if [[ -z ${DIR_RAW} ]]; then
  DIR_RAW="${DIR_PROJECT}/rawdata/${IDDIR}/anat"
fi
if [[ -z ${DIR_NATIVE} ]]; then
  DIR_NATIVE="${DIR_PROJECT}/derivatives/${PIPE}/anat/native"
fi
if [[ -z ${DIR_ADD} ]]; then
  ## update with additional directories as the come online with various workflows
  if [[ -d ${DIR_PROJECT}/derivatives/${PIPE}/anat/native_qmri ]]; then
    DIR_ADD="${DIR_PROJECT}/derivatives/${PIPE}/anat/native_qmri"
  fi
fi
DIR_ADD=(${DIR_ADD//,/ })
if [[ -z ${DIR_MASK} ]]; then
  DIR_MASK=${DIR_PROJECT}/derivatives/${PIPE}/anat/mask
fi
if [[ -z ${DIR_LABEL} ]]; then
  DIR_LABEL=${DIR_PROJECT}/derivatives/${PIPE}/anat/label
fi
if [[ -z ${DIR_POSTERIOR} ]]; then
  DIR_POSTERIOR=${DIR_PROJECT}/derivatives/${PIPE}/anat/posterior
fi
if [[ -z ${DIR_XFM} ]]; then
  DIR_XFM=${DIR_PROJECT}/derivatives/${PIPE}/xfm/${IDDIR}
fi
if [[ -z ${DIR_SAVE} ]]; then
  DIR_SAVE=${DIR_PROJECT}/derivatives/${PIPE}/anat/qc
fi
if [[ -z ${DIR_SUMMARY} ]]; then
  DIR_SUMMARY=${DIR_PROJECT}/summary
fi

# set output files and initialize with header as needed ----------------------
HDR="participant_id"
if [[ ${IDVARS[@]} == *"ses"* ]]; then HDR="${HDR},session-id"; fi
if [[ ${#IDVARS[@]} -gt 2 ]]; then 
  for (( i=2; i<${#IDVARS[@]}; i++ )); do
    HDR="${HDR},${IDVARS[${i}]}"
  done
fi
HDR="${HDR},dateCalculated,processingStage,imageType,\
cjv,cnr,efc,fber,snr_frame,snr_fg,snr_brain,snr_dietrich,wm2max,fwhm_x,fwhm_y,fwhm_z,\
rpve_gm,rpve_deepgm,rpve_wm,rpve_csf"
CSV_SUMMARY=${DIR_SUMMARY}/${PI}_${PROJECT}_QC-anat_summary.csv
if [[ ! -f ${CSV_SUMMARY} ]]; then echo ${HDR} > ${CSV_SUMMARY}; fi
CSV_PX=${DIR_SAVE}/${IDPFX}_qc-anat_${TIMESTAMP}.csv
if [[ ! -f ${CSV_PX} ]]; then echo ${HDR} > ${CSV_PX}; fi

if [[ "${NO_LOG}" == "false" ]]; then
  if [[ ! -f ${TKNI_LOG}/log_QCANAT.csv ]]; then
    echo "pi,project,id,timestamp,stage,modality,volume,metric,value" > ${TKNI_LOG}/log_QCANAT.csv
  fi
fi

# Find images -------------------------------------------------------------------
IMGS_RAW=($(ls ${DIR_RAW}/${IDPFX}*.nii.gz))
IMGS_NATIVE=($(ls ${DIR_NATIVE}/${IDPFX}*.nii.gz))
for (( i=0; i<${#DIR_ADD[@]}; i++ )); do
  IMGS_NATIVE+=($(ls ${DIR_ADD[${i}]}/${IDPFX}*.nii.gz))
done

# Copy to scratch (and push raw to native space) ---------------------------------
if [[ -z ${REF_NATIVE} ]]; then REF_NATIVE=${DIR_NATIVE}/${IDPFX}_T1w.nii.gz; fi
unset IMGS TYPES
for (( i=0; i<${#IMGS_RAW[@]}; i++ )); do
  IMG=${IMGS_RAW[${i}]}
  PFX=$(getBidsBase -i ${IMG} -s)
  MOD=$(getField -i ${IMG} -f modality)
  NV=$(niiInfo -i ${IMG} -f volumes)
  TYPES+=("raw")
  IMGS+=("${DIR_SCRATCH}/${IMG}")
  XFMFCN="antsApplyTransforms -d 3 -n Linear"
  if [[ ${NV} -gt 1 ]]; then XFMFCN="${XFMFCN} -e 3"; fi
  XFMFCN="${XFMFCN} -i ${IMG} -o ${DIR_SCRATCH}/${PFX}_${MOD}.nii.gz -r ${REF_NATIVE}"
  if [[ -f ${DIR_XFM}/${IDPFX}_from-${MOD}_from-raw_to-ACPC_xfm-rigid.mat ]]; then
    XFMSTR="${DIR_XFM}/${IDPFX}_from-${MOD}_from-raw_to-ACPC_xfm-rigid.mat"
  else
    XFMSTR="-t ${DIR_XFM}/${IDPFX}_from-${MOD}_to-native_xfm-syn.nii.gz"
    XFMSTR="${XFMSTR} -t ${DIR_XFM}/${IDPFX}_from-${MOD}_to-native_xfm-affine.mat"
  fi
  XFMFCN="${XFMFCN} -t identity -t ${XFMSTR}"
  eval ${XFMSTR}
done

for (( i=0; i<${#IMGS_NATIVE[@]}; i++ )); do
  TYPES+=("clean")
  IMGS+=("${IMGS_NATIVE[${i}]}")
done

# find masks and labels ========================================================
# find/create frame masks ------
for (( i=0; i<${#IMGS_RAW[@]}; i++ )); do
  IMG=${IMGS_RAW[${i}]}
  PFX=$(getBidsBase -i ${IMG} -s)
  MOD=$(getField -i ${IMG} -f modality)
  TFRAME=${DIR_MASK}/${IDPFX}_mod-${MOD}_mask-frame.nii.gz
  if [[ ! -f ${TFRAME} ]]; then
    # consider moving frame mask creation to AINIT and AMOD
    if [[ -f ${DIR_XFM}/${IDPFX}_from-${MOD}_from-raw_to-ACPC_xfm-rigid.mat ]]; then
      XFMSTR="${DIR_XFM}/${IDPFX}_from-${MOD}_from-raw_to-ACPC_xfm-rigid.mat"
    else
      XFMSTR="-t ${DIR_XFM}/${IDPFX}_from-${MOD}_to-native_xfm-syn.nii.gz"
      XFMSTR="${XFMSTR} -t ${DIR_XFM}/${IDPFX}_from-${MOD}_to-native_xfm-affine.mat"
    fi
    3dcalc -a ${IMG}[0] -expr a -overwrite -prefix ${TFRAME}
    niimath ${TFRAME} -mul 0 -add 1 ${TFRAME} -odt char
    XFMFCN="antsApplyTransforms -d 3 -n Linear"
    XFMFCN="${XFMFCN} -i ${TFRAME} -o ${TFRAME}.nii.gz -r ${REF_NATIVE}"
    XFMFCN="${XFMFCN} -t identity -t ${XFMSTR}"
    eval ${XFMSTR}
  fi
done

if [[ -z ${MASK_FG} ]]; then MASK_FG=${DIR_MASK}/${IDPFX}_mask-fg.nii.gz; fi
if [[ -z ${MASK_BRAIN} ]]; then MASK_BRAIN=${DIR_MASK}/${IDPFX}_mask-brain.nii.gz; fi
if [[ -z ${LABEL_TISSUE} ]]; then LABEL_TISSUE=${DIR_LABEL}/${IDPFX}_label-tissue.nii.gz; fi
if [[ -z ${MASK_WM} ]]; then MASK_WM=${DIR_MASK}/${IDPFX}_mask-wm.nii.gz; fi
if [[ ! -f ${MASK_WM} ]]; then
  niimath ${LABEL_TISSUE} -thr ${LAB_WM} -uthr ${LAB_WM} -bin ${MASK_WM} -odt char
fi
if [[ -z ${POSTERIOR_TISSUE} ]]; then
  POSTERIOR_TISSUE=${DIR_POSTERIOR}/${IDPFX}_posterior-tissue.nii.gz
fi

# CALCULATE METRICS ===============================================================
NIMG=${#IMGS[@]}
for (( i=0; i<${NIMG}; i++ )); do
  IMG=${IMGS[${i}]}
  PFX=$(getBidsBase -i ${IMG} -s)
  MOD=$(getField -i ${IMG} -f modality)
  NV=$(niiInfo -i ${IMG} -f volumes)
  FRAME=${DIR_MASK}/${IDPFX}_mod-${MOD}_mask-frame.nii.gz
  OPFX="${IDSTR},${TIMESTAMP},${TYPE[${i}]},${MOD}"
  
  unset CJV CNR EFC FBER RPVE SNR_FRAME SNR_FG SNR_BRAIN SNR_D WM2MAX FWHM
  CJV=($(qc_cjv --image ${IMG} --tissue ${LAB_TISSUE} --label "${LAB_GM},${LAB_WM}" --add-mean))
  CNR=($(qc_cnr --image ${IMG} --fg ${MASK_FG} --tissue ${LAB_TISSUE} --label "${LAB_GM},${LAB_WM}" --add-mean))
  EFC=($(qc_efc --image ${IMG} --frame ${FRAME} --add-mean))
  FBER=($(qc_fber --image ${IMG} --mask ${MASK_FG} --add-mean))
  SNR_FRAME=($(qc_snr --image ${IMG} --mask ${FRAME} --add-mean))
  SNR_FG=($(qc_snr --image ${IMG} --mask ${MASK_FG} --add-mean))
  SNR_BRAIN=($(qc_snr --image ${IMG} --mask ${MASK_BRAIN} --add-mean))
  SNR_D=($(qc_snrd --image ${IMG} --frame ${FRAME} --fg ${MASK_FG} --add-mean))
  WM2MAX=($(qc_wm2max --image ${IMG} --mask ${MASK_WM} --add-mean))
  FWHM=($(qc_fwhm --image ${IMG} --mask ${MASK_FG}))
  PIESNO=($(qc_piesnoish --image ${IMG} --mask ${MASK_BRAIN} --add-mean))

  OSTR="${CJV[-1]},${CNR[-1]},${EFC[-1]},${FBER[-1]},\
${SNR_FRAME[-1]},${SNR_FG[-1]},${SNR_BRAIN[-1]},${SNR_D[-1]},\
${WM2MAX[-1]},${FWHM[0]},${FWHM[1]},${FWHM[2]},${PIESNO[-1]},NA,NA,NA,NA"
  echo "${IDSTR},${TIMESTAMP},${TYPE[${i}]},${MOD},${OSTR}" | tee -a ${CSV_PROJECT} ${CSV_PX}
  
  if [[ "${NO_LOG}" == "false" ]]; then
    OPFX="${PI},${PROJECT},${IDPFX},${TIMESTAMP},${TYPE[${i}]},${MOD}"
    for (( j=0; j<${NV}; j++ )); do
      echo "${OPFX},${j},cjv,${CJV[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},cnr,${CNR[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},efc,${EFC[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},fber,${FBER[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},snr_frame,${SNR_FRAME[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},snr_fg,${SNR_FG[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},snr_brain,${SNR_BRAIN[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},snr_dietrich,${SNR_D[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},wm2max,${WM2MAX[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
      echo "${OPFX},${j},piesno,${PIESNO[${j}]}" >> ${TKNI_LOG}/log_QCANAT.csv
    done
    echo "${OPFX},NA,fwhm_x,${FWHM[0]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},NA,fwhm_y,${FWHM[1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},NA,fwhm_z,${FWHM[2]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,cjv,${CJV[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,cnr,${CNR[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,efc,${EFC[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,fber,${FBER[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv}
    echo "${OPFX},mean,snr_frame,${SNR_FRAME[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,snr_fg,${SNR_FG[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,snr_brain,${SNR_BRAIN[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,snr_dietrich,${SNR_D[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,wm2max,${WM2MAX[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
    echo "${OPFX},mean,piesno,${PIESNO[-1]}" >> ${TKNI_LOG}/log_QCANAT.csv
  fi
done

RPVE=($(qc_rpve --posterior ${POSTERIOR_TISSUE})))
OSTR="NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,${RPVE[0]},${RPVE[1]},${RPVE[2]},${RPVE[3]}"
echo "${IDSTR},${TIMESTAMP},NA,NA,${OSTR}" | tee -a ${CSV_PROJECT} ${CSV_PX}
if [[ "${NO_LOG}" == "false" ]]; then
  OPFX="${PI},${PROJECT},${IDPFX},${TIMESTAMP},NA,NA"
  echo "${OPFX},NA,rpve_gm,${RPVE[0]}" >> ${TKNI_LOG}/log_QCANAT.csv
  echo "${OPFX},NA,rpve_deepgm,${RPVE[1]}" >> ${TKNI_LOG}/log_QCANAT.csv
  echo "${OPFX},NA,rpve_wm,${RPVE[2]}" >> ${TKNI_LOG}/log_QCANAT.csv
  echo "${OPFX},NA,rpve_csf,${RPVE[3]}" >> ${TKNI_LOG}/log_QCANAT.csv
fi

# set status file --------------------------------------------------------------
mkdir -p ${DIR_PROJECT}/status/${PIPE}${FLOW}
touch ${DIR_PROJECT}/status/${PIPE}${FLOW}/CHECK_${PIPE}${FLOW}_${IDPFX}.txt

#===============================================================================
# End of Function
#===============================================================================
exit 0
