#!/bin/bash -e
#===============================================================================
# Wrapper to extract some basic info from NIfTI headers
# Authors: Timothy R. Koscik, PhD
# Date: 2021-01-28
#===============================================================================
# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hi:f: --long image:,field:,help -n 'parse-options' -- "$@")
if [[ $? != 0 ]]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
IMAGE=
FIELD=
HELP=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -i | --image) IMAGE="$2" ; shift 2 ;;
    -f | --field) FIELD="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "TKNI: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo '  -h | --help              display command help'
  echo '  -i | --image <value>     nii or nii.gz file'
  echo '  -f | --field <value>     string indicating information to extract'
  echo '    named NIfTI header fields'
  echo '    "origin"'
  echo '    "spacing" | "space"                   3D voxel size in mm'
  echo '    "size" | "voxels"                     3D voxel number'
  echo '    "voxel size" | "mm3"                  voxel volume'
  echo '    "vols" | "volumes" | "numtr" | "trs"  number of volumes, 4th dimension'
  echo '    "tr"                                  TR timing (s)'
  echo '    "orient" | "orientation"              image orientation'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
unset OUTPUT
if [[ "${FIELD,,}" == "origin" ]]; then
  TX=($(nifti_tool -disp_hdr -field srow_x -quiet -infiles ${IMAGE}))
  TY=($(nifti_tool -disp_hdr -field srow_y -quiet -infiles ${IMAGE}))
  TZ=($(nifti_tool -disp_hdr -field srow_z -quiet -infiles ${IMAGE}))
  TORIENT=($(3dinfo -orient ${IMAGE}))
  if [[ ${TORIENT} == *"L"* ]]; then
    TX[-1]=$(echo "scale=3; ${TX[-1]} * -1" | bc -l)
  fi
  if [[ ${TORIENT} == *"P"* ]]; then
    TY[-1]=$(echo "scale=3; ${TY[-1]} * -1" | bc -l)
  fi
  if [[ ${TORIENT} == *"I"* ]]; then
    TZ[-1]=$(echo "scale=3; ${TZ[-1]} * -1" | bc -l)
  fi
  OUTPUT=(${TX[-1]} ${TY[-1]} ${TZ[-1]})
elif [[ "${FIELD,,}" == "spacing" ]] || [[ "${FIELD,,}" == "space" ]]; then
  OUTPUT=($(nifti_tool -disp_hdr -field pixdim -quiet -infiles ${IMAGE}))
  OUTPUT=(${OUTPUT[@]:1:3})
elif [[ "${FIELD,,}" == "size" ]] || [[ "${FIELD,,}" == "voxels" ]]; then
  OUTPUT=($(nifti_tool -disp_hdr -field dim -quiet -infiles ${IMAGE}))
  OUTPUT=(${OUTPUT[@]:1:3})
elif [[ "${FIELD,,}" == "voxel size" ]] || [[ "${FIELD,,}" == "mm3" ]]; then
  TEMP=($(nifti_tool -disp_hdr -field pixdim -quiet -infiles ${IMAGE}))
  TEMP=(${TEMP[@]:1:3})
  OUTPUT=$(expr "${TEMP[0]} * ${TEMP[1]} * ${TEMP[2]}" | bc -l)
elif [[ "${FIELD,,}" == "vols" ]] || [[ "${FIELD,,}" == "volumes" ]] || [[ "${FIELD,,}" == "numtr" ]] || [[ "${FIELD,,}" == "trs" ]]; then
  OUTPUT=($(nifti_tool -disp_hdr -field dim -quiet -infiles ${IMAGE}))
  OUTPUT=(${OUTPUT[@]:4:1})
elif [[ "${FIELD,,}" == "tr" ]]; then
  OUTPUT=($(nifti_tool -disp_hdr -field pixdim -quiet -infiles ${IMAGE}))
  OUTPUT=(${OUTPUT[@]:4:1})
elif [[ "${FIELD,,}" == "orient" ]] || [[ "${FIELD,,}" == "orientation" ]]; then
  OUTPUT=($(3dinfo -orient ${IMAGE}))
else
  OUTPUT=($(nifti_tool -disp_hdr -field ${FIELD} -quiet -infiles ${IMAGE}))
fi
echo ${OUTPUT[@]}

#===============================================================================
# End of Function
#===============================================================================
exit 0

