#!/bin/bash -e
#===============================================================================
# <<DESCRIPTION>>
# Authors: <GIVENNAME> <FAMILYNAME>,
# Date: <date of initial commit>
# CHANGELOG: <description of major changes to functionality>
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
OPERATOR=${OPERATOR//@}
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch --------------------------------
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ ${EXIT_CODE} -eq 0 ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    writeBenchmark ${OPERATOR} ${HARDWARE} ${KERNEL} ${FCN_NAME} \
      ${PROC_START} ${PROC_STOP} ${EXIT_CODE}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hvl --long image:,mask:,dir-scratch:,\
help,verbose,no-log -n 'parse-options' -- "$@")
if [ $? != 0 ]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
IMAGE=
MASK=
DIR_SCRATCH=${TKNI_SCRATCH}/${FCN_NAME}_${OPERATOR}_${DATE_SUFFIX}
HELP=false
VERBOSE=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -v | --verbose) VERBOSE=1 ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    --image) IMAGE="$2" ; shift 2 ;;
    --mask) MASK="$2" ; shift 2 ;;
    --dir-scratch) DIR_SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "TKNI: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo 'Foreground / Background Energy Ratio (FBER):'
  echo 'The mean energy of image values within the head relative to outside the'
  echo 'head. Higher values are better, and an FBER=-1.0 indicates that there is'
  echo 'no signal outside the head mask (e.g., a skull-stripped dataset).'
  echo '    Shehzad Z. Preprocessed Connectomes Project Quality Assessment'
  echo '      Protocol - resource measuring quality MRI data, Front. Front'
  echo '      Neurosci Conference Abstract: Neuroinformatics. 2015;'
  echo '      http://dx.doi.org/10.3389/conf.fnins.2015.91.00047'
  echo ''
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  --image    <required>    NIfTI image to calculate stats for'
  echo '  --mask                   binary mask indicating foreground region'
  echo '  --dir-scratch            location for temporary files'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
mkdir -p ${DIR_SCRATCH}

niimath ${MASK} -binv ${DIR_SCRATCH}/mask-inv.nii.gz
niimath ${IMAGE} -mul ${IMAGE} ${DIR_SCRATCH}/image_sq.nii.gz
FGMED=($(3dROIstats -mask ${MASK} -median ${DIR_SCRATCH}/image_sq.nii.gz))
FGMED=${FGMED[-1]}
BGMED=($(3dROIstats -mask ${DIR_SCRATCH}/mask-inv.nii.gz -median ${DIR_SCRATCH}/image_sq.nii.gz))
BGMED=${BGMED[-1]}

if [[ "${BGMED}" == "0.000000" ]]; then
  FBER=-1
else
  FBER=$(echo "scale=4; ${FGMED} / ${BGMED}" | bc -l)
fi
echo ${FBER}

#===============================================================================
# End of Function
#===============================================================================
exit 0

