#!/bin/bash -e
#===============================================================================
# <<DESCRIPTION>>
# Authors: <GIVENNAME> <FAMILYNAME>,
# Date: <date of initial commit>
# CHANGELOG: <description of major changes to functionality>
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
OPERATOR=${OPERATOR//@}
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch --------------------------------
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ ${EXIT_CODE} -eq 0 ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    writeBenchmark ${OPERATOR} ${HARDWARE} ${KERNEL} ${FCN_NAME} \
      ${PROC_START} ${PROC_STOP} ${EXIT_CODE}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hvl --long image:,mask:,plane:,dir-scratch:,\
help,verbose,no-log -n 'parse-options' -- "$@")
if [ $? != 0 ]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
TS=
MASK=
XY="x,y,z"
DIR_SCRATCH=${TKNI_SCRATCH}/${FCN_NAME}_${OPERATOR}_${DATE_SUFFIX}
HELP=false
VERBOSE=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -v | --verbose) VERBOSE=1 ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    --ts) TS="$2" ; shift 2 ;;
    --mask) MASK="$2" ; shift 2 ;;
    --plane) XY="$2" ; shift 2 ;;
    --dir-scratch) DIR_SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "TKNI: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo 'Ghost to Signal Ratio (GhostR)'
  echo 'The GhostR estimates the mean signal in the areas of the image that are'
  echo 'prone to N/2 ghosts on the phase encoding direction with respect to the'
  echo 'mean signal within the brain mask. Lower values are better'
  echo '    Giannelli M, Diciotti S, Tessa C, Mascalchi M. Characterization'
  echo '    Nyquist ghost EPI-fMRI acquisition sequences implemented two'
  echo '    clinical 1.5 T MR scanner systems: efect readout bandwidth echo'
  echo '    spacing. J Appl Clin Med Phys. 2010;11.'
  echo ''
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  --image    <required>    NIfTI image to calculate stats for'
  echo '  --mask     <required>    binary mask indicating foreground region'
  echo '  --dir-scratch            location for temporary files'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
mkdir -p ${DIR_SCRATCH}

XY=(${XY//,/ })
IMGDIMS=($(niiInfo -i ${TS} -f size))
GHOST=${DIR_SCRATCH}/ghost.nii.gz
NONGHOST=${DIR_SCRATCH}/nonghost.nii.gz
for (( i=0; i<${#XY[@]}; i++ )); do
  if [[ "${XY[${i}],,}" == "x" ]]; then
    WRAP="$((${IMGDIMS[0]}/2))x0x0"
  elif [[ "${XY[${i}],,}" == "y" ]]; then
    WRAP="0x$((${IMGDIMS[1]}/2))x0"
  elif [[ "${XY[${i}],,}" == "z" ]]; then
    WRAP="0x0x$((${IMGDIMS[0]}/2))"
  fi
  c3d ${MASK} -wrap ${WRAP} ${GHOST}
  CopyImageHeaderInformation ${MASK} ${GHOST} 1 1 1
  niimath ${GHOST} -sub ${MASK} -thr 1 -bin ${GHOST}
  niimath ${MASK} -add ${GHOST} -binv ${NONGHOST}
  S=($(3dROIstats -mask ${MASK} -quiet ${TS}))
  G=($(3dROIstats -mask ${GHOST} -quiet ${TS}))
  NG=($(3dROIstats -mask ${NONGHOST} -quiet ${TS}))
  TGSR=0
  NTR=${#S[@]}
  for (( j=0; j<${NTR}; j++ )); do
    TMP=$(echo "scale=4; (${G[0]} -${NG[0]}) / ${S[0]}" | bc -l)
    TGSR=$(echo "scale=4; ${TGSR} + (${TMP} / ${NTR})" | bc -l)
  done
  GSR+=(${TGSR})
done
echo ${GSR[@]}

#===============================================================================
# End of Function
#===============================================================================
exit 0
