#!/bin/bash -e
#===============================================================================
# <<DESCRIPTION>>
# Authors: <GIVENNAME> <FAMILYNAME>,
# Date: <date of initial commit>
# CHANGELOG: <description of major changes to functionality>
#===============================================================================
PROC_START=$(date +%Y-%m-%dT%H:%M:%S%z)
FCN_NAME=($(basename "$0"))
DATE_SUFFIX=$(date +%Y%m%dT%H%M%S%N)
OPERATOR=$(whoami)
OPERATOR=${OPERATOR//@}
KERNEL="$(uname -s)"
HARDWARE="$(uname -m)"
NO_LOG=false
umask 007

# actions on exit, write to logs, clean scratch --------------------------------
function egress {
  EXIT_CODE=$?
  PROC_STOP=$(date +%Y-%m-%dT%H:%M:%S%z)
  if [[ ${EXIT_CODE} -eq 0 ]]; then
    if [[ -n ${DIR_SCRATCH} ]]; then
      if [[ -d ${DIR_SCRATCH} ]]; then
        if [[ "$(ls -A ${DIR_SCRATCH})" ]]; then
          rm -R ${DIR_SCRATCH}
        else
          rmdir ${DIR_SCRATCH}
        fi
      fi
    fi
  fi
  if [[ "${NO_LOG}" == "false" ]]; then
    writeBenchmark ${OPERATOR} ${HARDWARE} ${KERNEL} ${FCN_NAME} \
      ${PROC_START} ${PROC_STOP} ${EXIT_CODE}
  fi
}
trap egress EXIT

# Parse inputs -----------------------------------------------------------------
OPTS=$(getopt -o hvl --long image:,mask:,\
volume:,add-mean,precision:,\
dir-scratch:,\
help,verbose,no-log -n 'parse-options' -- "$@")
if [ $? != 0 ]; then
  echo "Failed parsing options" >&2
  exit 1
fi
eval set -- "$OPTS"

# Set default values for function ---------------------------------------------
IMAGE=
MASK=
VOLUME="all"
ADD_MEAN="false"
PRECISION=4
DIR_SCRATCH=${TKNI_SCRATCH}/${FCN_NAME}_${OPERATOR}_${DATE_SUFFIX}
HELP=false
VERBOSE=false

while true; do
  case "$1" in
    -h | --help) HELP=true ; shift ;;
    -v | --verbose) VERBOSE=1 ; shift ;;
    -l | --no-log) NO_LOG=true ; shift ;;
    --image) IMAGE="$2" ; shift 2 ;;
    --mask) MASK="$2" ; shift 2 ;;
    --volume) VOLUME="$2" ; shift 2 ;;
    --add-mean) ADD_MEAN="true" ; shift 2 ;;
    --precision) PRECISION="$2" ; shift 2 ;;
    --dir-scratch) DIR_SCRATCH="$2" ; shift 2 ;;
    -- ) shift ; break ;;
    * ) break ;;
  esac
done

# Usage Help -------------------------------------------------------------------
if [[ "${HELP}" == "true" ]]; then
  echo ''
  echo '------------------------------------------------------------------------'
  echo "TKNI: ${FCN_NAME}"
  echo '------------------------------------------------------------------------'
  echo 'White Matter to Maximum Intensity Ratio (WM2MAX)'
  echo 'The WM2MAX ratio is the median intensity within the WM mask over the 95%'
  echo 'percentile of the full intensity distribution, that captures the'
  echo 'existence of long tails due to hyper-intensity of the carotid vessels'
  echo 'and fat. Values should be around the interval [0.6, 0.8]'
  echo ''
  echo '  -h | --help              display command help'
  echo '  -l | --no-log            disable writing to output log'
  echo '  --image    <required>    NIfTI image to calculate stats for'
  echo '  --mask     <required>    binary mask indicating foreground region'
  echo '  --dir-scratch            location for temporary files'
  echo ''
  NO_LOG=true
  exit 0
fi

#===============================================================================
# Start of Function
#===============================================================================
NV=$(niiInfo -i ${IMAGE} -f volumes)
if [[ ${VOLUME} == "all" ]]; then
  VOLUME=($(seq 0 $((${NV}-1))))
else
  VOLUME=(${VOLUME//,/ })
fi

VAL_M=0
mkdir -p ${DIR_SCRATCH}
for i in "${VOLUME[@]}"; do
  TIMG=${DIR_SCRATCH}/IMG.nii.gz
  3dcalc -a ${IMAGE}[${i}] -expr a -overwrite -prefix ${TIMG}
  WMMED=($(3dROIstats -mask ${MASK} -quiet -median ${TIMG}))
  IMGPCT=($(3dBrickStat -perclist 1 95 ${TIMG}))
  TVAL=$(echo "scale=6; ${WMMED[-1]} / ${IMGPCT}" | bc -l)
  if [[ ${ADD_MEAN} == "true" ]] && [[ ${NV} -gt 1 ]]; then
    VAL_M=$(echo "scale=6; (${TVAL} + ${VAL_M}) / ${#VOLUME[@]}" | bc -l)
  fi
  VAL+=($(printf "%.*f" ${PRECISION} ${TVAL}))
done
if [[ ${ADD_MEAN} == "true" ]] && [[ ${NV} -gt 1 ]]; then
  VAL+=($(printf "%.*f" ${PRECISION} ${VAL_M}))
fi
echo ${VAL[@]}

#===============================================================================
# End of Function
#===============================================================================
exit 0
